[package]
name = "ReplicladeRust"
version = "0.1.0"
edition = "2021"
authors = ["Haki Dehari"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "0.28.2"